server:
  port: 10000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.219.9.104:3308/lofter_qa_backend?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 49.234.47.124
    port: 60002
    password:
    timeout: 3000


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      test:
        springboot:
          entity:
        mapper : debug